---
- hosts: all
  become: true

  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"

  roles:
    - role: os_update
      tags:
        - always
        - os_update
      vars:
        upgrade_type: full

    - role: common
      tags: common

    - role: keychron
      tags: keychron

    - role: nextcloud
      tags: nextcloud

    - role: jenkins
      tags: jenkins
