---
# $ ansible-playbook --ask-become-pass site.yml
- hosts: gk41
  become: true

  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"

  roles:
    - role: os_update
      tags:
        - always
        - os_update
      vars:
        upgrade_type: full

    - role: keychron
      tags: keychron
    - role: nextcloud
      tags: nextcloud
