---
- hosts: gk41
  become: true

  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"

  roles:
    - role: os_update
      tags:
        - always
        - os_update
      vars:
        upgrade_type: full

    - role: common
      tags: common
      vars:
        home_dir: /home/server

    - role: keychron
      tags: keychron
    - role: nextcloud
      tags: nextcloud
