---
# Enable function keys works with keychron keyboard
- name: copy command to /usr/local/bin/
  ansible.builtin.copy:
    src: keychron
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0751'
  register: bin_keychron

- debug: 
    var: bin_keychron.failed

- name: copy service to /etc/systemd/system/
  ansible.builtin.copy:
    src: keychron.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  register: system_keychron

- debug: 
    var: system_keychron.failed

# systemctl status keychron will have failed status
# if no keychron keyboard is plugged in
- name: starts keychron.service
  ansible.builtin.service:
    name: keychron
    enabled: yes
  when: bin_keychron.failed == false and system_keychron.failed == false
