---
- name: configure Samba
  block:
    - name: install samba
      apt:
        pkg:
          - samba
          - f2fs-tools

    - name: create directory for samba mount
      ansible.builtin.file:
        path: "{{ sambashare }}"
        state: directory
        mode: '0777'

    - name: "Mount SSD for samba directory"
      ansible.posix.mount:
        path: "{{ sambashare }}"
        src: "UUID=a1efd63d-2daa-444f-b4b7-2a2034a6580d"
        fstype: f2fs
        opts: noatime,auto,noexec,rw,sync
        state: mounted

    - name: Allow http and ssh port
      community.general.ufw:
        rule: allow
        name: samba

    - name: Enable samba service
      ansible.builtin.service:
        name: smbd
        enabled: true

    - name: Account Setup
      ansible.builtin.debug:
        msg: |
          To create a samba account: $ sudo smbpasswd -a $username,
          Only works if account is already existed in system itself.
  notify: restart-samba.service
