---
# roles/nextcloud/tasks/

- name: Allow http and ssh port
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:  # service names: /etc/services
    - ssh
    - http
    - https
    - mysql

- name: Create a self-signed certificate
  vars:
    ssl_path: /etc/ssl/self-signed

  block:
    - name: Create directory
      file:
        path: "{{ ssl_path }}"
        state: directory
        owner: root
        group: root
        mode: '0655'

    - name: Copy private key
      ansible.builtin.copy:
        src: .ssl/server.lan.key
        dest: "{{ ssl_path }}"
        owner: root
        group: root
        mode: '0600'

    - name: Copy self-signed certificate
      ansible.builtin.copy:
        src: .ssl/server.lan.crt
        dest: "{{ ssl_path }}"
        owner: root
        group: root
        mode: '0644'

- name: Setup and enable nextcloud on startup
  vars:
    systemd_service_path: /etc/systemd/system/

  block:
    - name: Build custom nextcloud image
      community.docker.docker_image:
        name: local/nextcloud:casc
        build:
          path: /srv/git/dockers/nextcloud
          args:
            EMAIL: "{{ EMAIL }}"
            DOMAIN: "{{ DOMAIN }}"
        source: build
      register: output

    - name: debug
      ansible.builtin.debug:
        msg: output


    - name: "Copy files to /srv/git/dockers/nextcloud"
      ansible.builtin.copy:
        src: .env
        dest: /srv/git/dockers/nextcloud
        owner: root
        group: root
        mode: '0644'

    - name: "Copy files to {{ systemd_service_path }}"
      ansible.builtin.copy:
        src: nextcloud.service
        dest: "{{ systemd_service_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Enable nextcloud.service
      ansible.builtin.service:
        name: nextcloud
        enabled: true
  notify: restart-nextcloud.service
...
