---
# nextcloud/tasks/

- name: Allow http and ssh port
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:  # service names: /etc/services
    - ssh
    - http
    - https
    - mysql

- name: Create a self-signed certificate
  vars:
    ssl_path: /etc/ssl/docker

  block:
    - name: Create directory
      file:
        path: "{{ ssl_path }}"
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: Copy private key
      ansible.builtin.copy:
        src: .ssl/server.lan.key
        dest: "{{ ssl_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Copy self-signed certificate
      ansible.builtin.copy:
        src: .ssl/nextcloud.lan.crt
        dest: "{{ ssl_path }}"
        owner: root
        group: root
        mode: '0644'

- name: Setup and enable nextcloud on startup
  vars:
    nextcloud_path: "{{ docker_path }}/nextcloud"
    systemd_service_path: /etc/systemd/system/

  block:
    - name: Pull Nextcloud from Docker
      community.docker.docker_image:
        name: nextcloud
        source: pull

    - name: "Create directory for docker in {{ nextcloud_path }}"
      file:
        path: "{{ nextcloud_path }}"
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: "Copy files to {{ nextcloud_path }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ nextcloud_path }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - .env
        - docker-compose.yml

    - name: "Copy files to {{ systemd_service_path }}"
      ansible.builtin.copy:
        src: nextcloud.service
        dest: "{{ systemd_service_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Enable nextcloud.service
      ansible.builtin.service:
        name: nextcloud
        enabled: true
  notify: restart-nextcloud.service
