---
- name: Install and enable Docker service and its libraries
  block:
    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: latest

    - name: Install Docker SDK for Python
      apt:
        name: python3-docker
        state: latest

    - name: Allow http and ssh port
      community.general.ufw:
        rule: allow
<<<<<<< HEAD
        port: ssh
=======
        port: "{{ item }}"
      loop:
        - ssh
        - http
        - https
        - mysql
>>>>>>> nextcloud

    - name: start docker.service
      ansible.builtin.service:
        name: docker
        enabled: true

    - name: Pull alpine from Docker
      community.docker.docker_image:
        name: alpine
        source: pull

    - name: Pull Nextcloud from Docker
      community.docker.docker_image:
        name: nextcloud
        source: pull
  notify: restart-docker.service
# end block

<<<<<<< HEAD
- name: Setup and enable nextcloud on startup
  vars:
    nextcloud_path: /etc/docker/nextcloud/
    systemd_service_path: /etc/systemd/system/
=======
- name: Setup docker volumes mount point
  vars:
    docker_volume_path: "/var/lib/device/docker_volume"
>>>>>>> nextcloud

  block:
    - name: "Create directory: {{ docker_volume_path }}"
      file:
        path: "{{ docker_volume_path }}"
        state: directory

    - name: "Change file permission on Docker Volumes directory"
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '1755'
      loop:
        - "{{ docker_volume_path }}"

    - name: "Mount SD Card for storing docker volumes"
      ansible.posix.mount:
        path: "{{ docker_volume_path }}"
        src: "UUID={{ docker_volume_device }}"
        fstype: ext4
        opts: noatime,auto,noexec,rw,sync
        state: mounted

# end block

- name: Setup and enable nextcloud on startup
  vars:
    nextcloud_path: /etc/docker/nextcloud/
    systemd_service_path: /etc/systemd/system/

  block:

    - name: "Create directory for docker in {{ nextcloud_path }}"
      file:
        path: "{{ nextcloud_path }}"
        state: directory

    - name: "Copy files to {{ nextcloud_path }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ nextcloud_path }}"
      loop:
        - .env
        - docker-compose.yml

    - name: "Copy files to {{ systemd_service_path }}"
      ansible.builtin.copy:
        src: nextcloud.service
        dest: "{{ systemd_service_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Enable nextcloud.service
      ansible.builtin.service:
        name: nextcloud
        enabled: true
  notify: restart-nextcloud.service

    # TODO: can't get docker-compose work -- doesn't reconize mariadb in compose file
