---
# common/tasks
- name: Install list of packages
  apt:
    pkg:
      - vim
      - silversearcher-ag
      - fd-find
      - f2fs-tools

- name: Change default editor to vim
  lineinfile:
    path: "/home/{{ ansible_user }}/.profile"
    regexp: '^export EDITOR='
    line: 'export EDITOR=/usr/bin/vim'

- name: Add environmental variables
  lineinfile:
    path: "/home/{{ ansible_user }}/.profile"
    regexp: '^export DOCKER='
    line: 'export DOCKER=/etc/docker/'

- name: Create directory
  file:
    path: "/home/{{ ansible_user }}/Source/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
