---
# common/tasks
- name: Install Micro
  apt:
    name: micro
    state: latest

- name: Install the silver searcher
  apt:
    name: silversearcher-ag
    state: latest

- name: Change default editor to micro
  lineinfile:
    path: "{{ home_dir }}/.profile"
    regexp: '^export EDITOR='
    line: 'export EDITOR=/usr/bin/micro'

- name: Add environmental variables
  lineinfile:
    path: "{{ home_dir }}/.profile"
    regexp: '^export DOCKER='
    line: 'export DOCKER=/etc/docker/'

- name: Create directory
  file:
    path: "{{ home_dir }}/Source/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
