---
# docker/tasks
- name: Install and enable Docker service and its libraries
  block:
    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: latest

    - name: Install Docker SDK for Python
      apt:
        name: python3-docker
        state: latest

    - name: start docker.service
      ansible.builtin.service:
        name: docker
        enabled: true

  notify: restart-docker.service
  # end block

- name: Git checkout
  ansible.builtin.git:
    repo: "{{ docker_repo }}"
    dest: "{{ docker_path }}"
    single_branch: true
    version: main
